---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 7-demo-source-oci-helm-bb-app-7-7-1
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: ghcr-auth
  type: oci
  url: oci://ghcr.io/sidd-harth/bb-app

